// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Ms_Palmer
{
    public partial class VMConfigurationOperatingSystemPredictionModel
    {
        /// <summary>
        /// model input class for VMConfigurationOperatingSystemPredictionModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"UseCase")]
            public string UseCase { get; set; }

            [ColumnName(@"OperatingSystem")]
            public string OperatingSystem { get; set; }

            [ColumnName(@"Size")]
            public float Size { get; set; }

            [ColumnName(@"OperatingSystemLicense")]
            public string OperatingSystemLicense { get; set; }

            [ColumnName(@"GuestAdditions")]
            public bool GuestAdditions { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for VMConfigurationOperatingSystemPredictionModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"UseCase")]
            public uint UseCase { get; set; }

            [ColumnName(@"OperatingSystem")]
            public uint OperatingSystem { get; set; }

            [ColumnName(@"Size")]
            public float Size { get; set; }

            [ColumnName(@"OperatingSystemLicense")]
            public string OperatingSystemLicense { get; set; }

            [ColumnName(@"GuestAdditions")]
            public bool GuestAdditions { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("VMConfigurationOperatingSystemPredictionModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
