
// This file was auto-generated by ML.NET Model Builder. 

using MLVMConfigurationModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLVMConfigurationModel.ModelInput sampleData = new MLVMConfigurationModel.ModelInput()
{
    UseCase = @"Education",
    OperatingSystem = @"Ubuntu",
    OperatingSystemLicense = @"N/A",
    GuestAdditions = false,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLVMConfigurationModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Size with predicted Size from sample data...\n\n");


Console.WriteLine($"UseCase: {@"Education"}");
Console.WriteLine($"OperatingSystem: {@"Ubuntu"}");
Console.WriteLine($"Size: {30720F}");
Console.WriteLine($"OperatingSystemLicense: {@"N/A"}");
Console.WriteLine($"GuestAdditions: {false}");


Console.WriteLine($"\n\nPredicted Size: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

